Update to latest @types/node
Some of the CI builds failed with

.../vscode-arduino/vscode-arduino/node_modules/@types/connect/index.d.ts(20,42): error TS2689: Cannot extend an interface 'http.IncomingMessage'. Did you mean 'implements'?
TypeScript: 1 semantic error

and apparently this is caused by old @types/node version (previously
version 6.14.9 in this project).

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/41828#issuecomment-605779004
https://stackoverflow.com/a/59988564/23118
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/41092