Update eslint to latest version and fix issues reported (#1352)
* Whitespace fixes in gulpfile.js

* Eslint: fix no-extra-semi

* Eslint: fix no-useless-escape

* Eslint: fix no-constant-condition

* Eslint: fix no-extra-boolean-cast

Also consistent with existing style in LibraryManager.tsx

* Eslint: fix no-prototype-builtins

* Eslint: fix prefer-const

* Eslint: fix no-var

* Eslint: fix no-case-declarations

* Remove unused selectedBoard in reducer

Added in commit 8895adee6b6 but never used at any time.

* Eslint: fix no-unused-vars

* Eslint: fix no-control-regex

* Eslint: fix react/no-deprecated

https://reactjs.org/docs/react-component.html#unsafe_componentwillmount

* Eslint: fix react/no-direct-mutation-state

* Add eslint configuration

Created with
    npx eslint --init
and added a couple of rule configurations manually.

Synchronize gulp.src between tslint and eslint.

* Update esllint to latest version

* npm install --save-dev @types/glob

* npm install --save-dev @types/uuid

* npm install --save-dev @types/express

* Remove unecessary await

* Update to latest @types/node

Some of the CI builds failed with

.../vscode-arduino/vscode-arduino/node_modules/@types/connect/index.d.ts(20,42): error TS2689: Cannot extend an interface 'http.IncomingMessage'. Did you mean 'implements'?
TypeScript: 1 semantic error

and apparently this is caused by old @types/node version (previously
version 6.14.9 in this project).

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/41828#issuecomment-605779004
https://stackoverflow.com/a/59988564/23118
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/41092